JuulLabs/krayon

chart/src/androidMain/kotlin/ChartView.kt, kanvas/build.gradle.kts, kanvas/src/androidMain/kotlin/AndroidPaint.kt, kanvas/src/androidTest/kotlin/AndroidPaintTests.kt
Just a couple of small issues I ran into now that I'm actually consuming this.
=> Fix fill paints on Android; remove restrictions from ChartView.Adapter

README.md, chart/src/commonMain/kotlin/render/Defaults.kt, chart/src/commonMain/kotlin/render/components/BarRenderer.kt, color/README.md, color/api/color.api, color/build.gradle.kts, color/gradle.properties, color/src/androidMain/AndroidManifest.xml, color/src/commonMain/kotlin/Color.kt, color/src/commonMain/kotlin/Constants.kt, color/src/commonMain/kotlin/Operations.kt, color/src/commonMain/kotlin/Random.kt, color/src/commonMain/kotlin/WebColors.kt, color/src/commonTest/kotlin/ColorTests.kt, kanvas/api/kanvas.api, kanvas/src/androidMain/kotlin/AndroidKanvas.kt, kanvas/src/androidTest/kotlin/AndroidPaintTests.kt, kanvas/src/commonMain/kotlin/Kanvas.kt, kanvas/src/commonMain/kotlin/Paint.kt, kanvas/src/commonMain/kotlin/svg/Paint.kt, kanvas/src/commonMain/kotlin/svg/SvgKanvas.kt, kanvas/src/commonTest/kotlin/CallRecordingKanvas.kt, kanvas/src/commonTest/kotlin/KanvasExtensionTests.kt, kanvas/src/commonTest/kotlin/SvgTests.kt, sample/api/sample.api, sample/src/main/java/com/juul/krayon/sample/CustomCanvasView.kt, sample/src/main/java/com/juul/krayon/sample/DemoActivity.kt, settings.gradle.kts
- Package change.
- Receiver on `lerp` removed in favor of function argument
- Color constants are no longer namespaced in the `Color` class
- Color constants updated to match [web colors](https://en.wikipedia.org/wiki/Web_colors#HTML_color_names)
Closes #20.
=> Split color into its own module

.github/workflows/gh-pages.yml, build.gradle.kts
Configured to publish updated Dokka documentation on every commit that is merged to `main`.
=> Setup publication of Dokka documentation to GitHub Pages

build.gradle.kts, chart/build.gradle.kts, color/api/color.api, color/build.gradle.kts, color/src/androidMain/AndroidManifest.xml, gradle/wrapper/gradle-wrapper.properties, kanvas/api/kanvas.api, kanvas/build.gradle.kts
Some dependency version bumps were needed to have Gradle play nice with Android modules depending on the JVM `color` module.
=> Drop Android and add JavaScript target to 'color' module

.github/workflows/ci.yml
Token is not necessary for public (open source) repositories.
Per codecov settings for the project:
=> Remove codecov token

.github/workflows/ci.yml, .github/workflows/gh-pages.yml, .github/workflows/publish.yml, .github/workflows/snapshot.yml, build.gradle.kts
Supports the latest version of `com.vanniktech.maven.publish` Gradle plugin that was updated in #31.
Adds Gradle wrapper validator.
Now properly supports building PRs from forks.
Also removes Mac OS X configuration (that was commented out), we can update CI scripts with Mac OS X configuration when we have a need for that virtual environment.
=> Update CI scripts and use in-memory ascii-armored key for signing

.gitignore, element-view/api/element-view.api, element-view/build.gradle.kts, element-view/src/androidMain/kotlin/ElementView.kt, element-view/src/androidMain/kotlin/ElementViewAdapter.kt, element-view/src/commonMain/kotlin/AdapterState.kt, element-view/src/commonMain/kotlin/ElementViewAdapter.kt, element-view/src/commonMain/kotlin/UpdateElement.kt, element-view/src/jsMain/kotlin/ElementViewAdapter.kt, element-view/src/jsMain/kotlin/HTMLCanvasElement.kt, kanvas/src/jsMain/kotlin/HtmlCanvas.kt, sample/build.gradle.kts, sample/src/androidMain/kotlin/com/juul/krayon/sample/DemoActivity.kt, sample/src/jsMain/kotlin/Main.kt
Extract's `ElementView.Adapter` to a common `ElementViewAdapter` to allow a simpler JS display implementation with automatic frame pacing. Eliminates stuttering on Chrome (on my macbook, at least. ymmv)
=> Add JS Canvas Frame Pacing

scale/api/scale.api, scale/src/commonMain/kotlin/Max.kt, scale/src/commonMain/kotlin/Min.kt
Useful for computing the domain of data when the data contains multiple values that may influence the min or max.
For example, `max` is used in [Line plot with several groups](https://www.d3-graph-gallery.com/graph/line_several_group.html) for computing the y-axis domain:
They were also used in https://github.com/JuulLabs/sensortag/pull/48.
=> Add `min` and `max` operators

color/build.gradle.kts
Needed by an internal project.
=> Add `macosX64` target to `color` module

gradle/libs.versions.toml
If the publish test succeeds I'll merge this. If it fails I won't. 
Maven publication was failing because modules that generated both JVM and Android targets were missing JavaDoc jar on JVM. This failed sonatype validation preventing publishing.
=> Revert version bump

compose/src/commonMain/kotlin/ComposeKanvas.kt
Compose's default pivot isn't `0, 0` so that's fun. `Offset` is actually a packed inline value class so we're not paying the GC tax to create one, so just always specify.
=> Fix a bug in the compose canvas

gradle.properties
Rather than specifying a version, we should use the default.
=> Drop usage of explicit Webpack version

.github/workflows/publish.yml
`color-macosx64` Maven artifact is missing because the `macosX64` target is not compiled when using Ubuntu virtual environment:
Switching to `macos` virtual environment should resolve the issue (and publish the `macosx64` artifacts).
=> Publish using `macos` virtual environment

compose/src/commonMain/kotlin/ComposeKanvas.kt
Fixes a bug in `ComposeKanvas`. This wasn't spotted earlier because `ElementView` doesn't directly use the `width`/`height` properties due to its deferred rendering logic.
=> Scale width and height of compose canvas correctly

kanvas/src/jsMain/kotlin/HtmlCanvas.kt, sample/src/commonMain/kotlin/PieChart.kt
Apparently conic ("sweep" in Android) gradients release in Chrome on March 1st this year, so let's support those.
=> Implement conic gradients for HTML/JS

element-view/src/jsMain/kotlin/HTMLCanvasElement.kt
Fixes a bug where resize events weren't being captured.
=> Use `ResizeObserver` instead of `onresize` callback for JS Element-View Adapter

kanvas/src/jsMain/kotlin/HtmlCanvas.kt
It turns out that CSS fonts don't handle quoting the built-ins of `serif`, `sans-serif`, and `monospace`. We can handle this by quoting only font names that contain whitespace, which is probably the right thing to do anyways.
=> Fix JS font fallback

kanvas/src/androidMain/kotlin/ScaledIsPointInPath.kt
Affects Elements that return the same path for multiple calls to `getInteractionPath`. Because I haven't been good about implementing path caching on most elements (yet), this was only affecting `PathElement` among the built-in element types.
=> Fix bug in Android interactions

axis/build.gradle.kts, box/build.gradle.kts, compose/build.gradle.kts, element-view/build.gradle.kts, element/build.gradle.kts, interpolate/build.gradle.kts, kanvas/build.gradle.kts, sample/build.gradle.kts, scale/build.gradle.kts, selection/build.gradle.kts, settings.gradle.kts, shape/build.gradle.kts
Enables Gradle [type-safe project dependencies](https://docs.gradle.org/7.0/userguide/declaring_dependencies.html#sec:type-safe-project-accessors).
Special thanks to [Jake Wharton](https://twitter.com/JakeWharton/status/1491116447703375873?s=20&t=OSmqu1G4hGUUHSh2br5pSQ):
```zsh
find . -type f -name 'build.gradle*' -exec gsed -i -e "/project(/s/-[a-z]/\U&/g" -e "/project(/s/:/./g" -e "/project(/s/-//g" -E -e "s/project\((path\. ?)?('|\")([^'\"]+)\2\)/projects\3/" {} \;
```
=> Use Gradle type-safe project accessors

element-view/src/commonMain/kotlin/AdapterState.kt, element-view/src/jsMain/kotlin/ElementViewAdapter.kt, element-view/src/jsMain/kotlin/HTMLCanvasElement.kt, kanvas/src/jsMain/kotlin/HtmlKanvas.kt, sample/src/jsMain/resources/index.html
We've supported this in Android for a while. Turns out we need it for JS too.
There's an opt-out provided, since it turns out DPI-scaling doesn't play nice with `canvas` intrinsic sizing. It's _better_ to define the size in CSS anyways, but it was pretty easy to support both configurations.
_Technically_ this is a major/breaking change since we default to the new behavior, but we're between major releases anyways so I'm not worried about it.
=> DPI scaling for JS/HTML

kanvas/src/jsMain/kotlin/ConicGradient.kt, kanvas/src/jsMain/kotlin/HtmlKanvas.kt
_Previously_ we handled conic gradient start angle by comparing to user agent string, which created a whack-a-mole approach to supporting browsers.
_Now_ we use an [`OffscreenCanvas`](https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas) to render a conic and determine behavior based on how it drew. This should work basically everywhere except Safari, but we can just catch Safari's crash and hard-code only that browser.
=> Improve logic for handling JS conic gradients

box/build.gradle.kts, gradle.properties, gradle/libs.versions.toml, kanvas/README.md, kanvas/api/android/kanvas.api, kanvas/api/jvm/kanvas.api, kanvas/build.gradle.kts, kanvas/src/commonMain/kotlin/Clip.kt, kanvas/src/commonMain/kotlin/Path.kt, kanvas/src/commonMain/kotlin/Transform.kt, kanvas/src/nativeDarwinMain/kotlin/CFString.kt, kanvas/src/nativeDarwinMain/kotlin/CGAffineTransform.kt, kanvas/src/nativeDarwinMain/kotlin/CGContextKanvas.kt, kanvas/src/nativeDarwinMain/kotlin/CGPathBuilder.kt, kanvas/src/nativeDarwinMain/kotlin/FontCache.kt, kanvas/src/nativeDarwinMain/kotlin/IsPointInCGPath.kt, kanvas/src/nativeDarwinMain/kotlin/Paint.kt, kanvas/src/nativeDarwinMain/kotlin/Text.kt
The basics of rendering and interaction are in (likely with bugs). Each Swift consumer will have to do its own equivalent for ElementView -- I'd like to publish a cocoapod or something, but the limitation of 1 kotlin library per Swift app means that you couldn't use it if you had your own Kotlin library to consume, which would lose the major advantage of using Krayon. 
In the future I'll publish a copy-pasteable snippet, but for now I'm happy with how this is _as a beta_.
=> Beta Apple (Mac OS & iOS) Support

element/api/element.api, element/src/commonMain/kotlin/ClipElement.kt, kanvas/src/nativeDarwinMain/kotlin/CGContextKanvas.kt
Adds a `ClipElement` -- missed earlier by accident.
Fixes a bug on iOS discovered while using said `ClipElement`
=> Add clip element and fix clipping bug on iOS

build.gradle.kts
We no longer use pre-release Compose versions.
=> Remove JetBrains Maven repository

renovate.json
Adds Renovate configuration which groups upgrades for Kotlin and Compose compiler into a single PR (as those dependencies are often tightly coupled together).
Inspired by [PaulWoitaschek/Voice/renovate.json](https://github.com/PaulWoitaschek/Voice/blob/08ddf39bb0283df92cdcb4ae14828aa1573a753a/renovate.json).
Example of Renovate PR created with grouping: https://github.com/PaulWoitaschek/Voice/pull/1832
=> Add Renovate configuration to combine Kotlin and Compose upgrades

scale/api/scale.api, scale/src/commonMain/kotlin/Nice.kt
Previously, krayon was missing the `nice` function from d3 for generating intervals. This should allow us to do so
=> Add 'nice' function from d3

.github/workflows/gh-pages.yml
I had seen `$default-branch` used and it seemed like a flexible way to trigger on merges to the "main" (default) branch, but apparently it [only works for workflow templates](https://stackoverflow.com/a/65723433). 😢 
As a result, the GitHit Pages deployment has not been triggered since merge of #306. This PR restores the previous explicit (`main`) branch trigger.
=> Use explicit branch name for GitHub pages workflow

.github/workflows/gh-pages.yml
According to [github-pages-deploy-action] documentation, `write` permission is necessary:
...should hopefully resolve failing [GitHub pages deployment](https://github.com/JuulLabs/krayon/actions/runs/7467024581/job/20319652791)s.
[github-pages-deploy-action]: https://github.com/JamesIves/github-pages-deploy-action
=> Give GitHub pages workflow `contents` write permission

settings.gradle.kts
Simplifies process of setting up project for contributors (JVM toolchain is automatically setup for project if not present on user's system).
=> Configure automatic JVM toolchain downloading

axis/build.gradle.kts, box/build.gradle.kts, color/build.gradle.kts, element/build.gradle.kts, hierarchy/build.gradle.kts, interpolate/build.gradle.kts, kanvas/build.gradle.kts, sample/build.gradle.kts, scale/build.gradle.kts, selection/build.gradle.kts, shape/build.gradle.kts, time/build.gradle.kts
Per [Kotlin/Native target support], the following targets fall under [tier 1]:
- `macosX64`
- `macosArm64`
- `iosSimulatorArm64`
- `iosX64`
This PR adds any missing tier 1 targets to any modules that had Native targets.
Also, sorted the targets while I was making changes.
[Kotlin/Native target support]: https://kotlinlang.org/docs/native-target-support.html
[tier 1]: https://kotlinlang.org/docs/native-target-support.html#tier-1
=> Add Native targets missing in tier 1

.github/workflows/gh-pages.yml, .github/workflows/release-drafter.yml
On forks (without GitHub pages setup — which is default) documentation deployment will fail (i.e. when fast-forwarding their `main` branch).
<details>
<summary>Example failure</summary>
</details>
Release drafting is also unnecessary for forks.
=> Skip `gh-pages` and `release-drafter` workflows on forks

.github/workflows/ci.yml
Should fix the following (which we're seeing in CI workflow runs):
> Warning: Running this action via 'uses: EnricoMi/publish-unit-test-result-action/composite@v2 is deprecated! For details, see: https://github.com/EnricoMi/publish-unit-test-result-action/tree/v2#running-as-a-composite-action
=> Update `publish-unit-test-result-action` GitHub action

build.gradle.kts
This is necessary to properly pull in Krayon as a [Gradle composite build](https://docs.gradle.org/current/userguide/composite_builds.html).
=> Globally configure Maven `group`

compose/build.gradle.kts, gradle.properties
Allows composable `ElementView` to be used from JavaScript. 🎉
=> Add JavaScript target to `compose` module

gradle.properties
Updates Sonatype host per [`gradle-maven-publish-plugin` release notes](https://github.com/vanniktech/gradle-maven-publish-plugin/releases/tag/0.33.0).
=> Use `CENTRAL_PORTAL` Sonatype host for publication

box/build.gradle.kts, compose/build.gradle.kts, element-view/build.gradle.kts, kanvas/build.gradle.kts, sample/build.gradle.kts
There is no need to fail builds/CI due to outdated dependencies.
=> Disable Android `GradleDependency` lint check

compose/src/skiaMain/kotlin/SkiaIsPointInPath.kt
`SkiaIsPointInPath` incorrectly mutated the cached path when hit testing points. 
This could have been solved less-invasively by just copying the skia path to a new buffer. But that introduces yet-another inefficiency on an already pretty inefficient function. Instead, I'm taking this opportunity to apply two optimizations:
1. Avoid allocating multiple matrices for `InOrder` transformation chains
2. Only apply the (inverse) transformation to the test-point instead of transforming the whole path
=> Fix: `SkiaIsPointInPath` should not mutate the Path buffer
